### PR TITLE
Adding docs and refactoring AWS provider. General cleanup of aws provider.

### PR DESCRIPTION
**Pull request by benhg**

### CODE REVIEW

**Comment by yadudoc** [comment]
Hey Ben, It looks like the travis build is failing from a bug in the code. Can you check please? The logs here should help https://travis-ci.org/Parsl/libsubmit/jobs/326593002

**Comment by benhg** [comment]
@yadudoc should work now. Thanks.

**Comment by yadudoc** [comment]
@benhg Looks like the build tests are failing, can you please check ?

**Comment by benhg** [comment]
@yadudoc should work now.

**Pull request merged**
