### PR TITLE
minor commas and spelling

### PR DESCRIPTION
**Pull request by danielskatz**

### CODE REVIEW

**Comment by annawoodard** [comment]
@danielskatz these look good, can you merge with master and we'll merge it?

**Comment by annawoodard** [comment]
(In the future we'll try to review PRs in both repositories quickly, so that there is less overhead keeping various branches synced)

**Comment by danielskatz** [comment]
I don't have permission to merge, but assuming you really mean "can you resolve the conflicts that have appeared since you first suggested the changes 3+ months ago" I will try to do so.

I will also point out that if this had been merged back in December, it would have been less work for everyone :)

**Comment by yadudoc** [comment]
Sorry Dan! Right around Dec, I rewrote a lot of the aws provider and a lot of dead code was removed. I should've merged first.

**Comment by danielskatz** [comment]
closing in favor of https://github.com/Parsl/libsubmit/pull/36

**Pull request closed without merging**
